version: "3.8"

services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    ports:
      - "514:514/udp"    # odbiór logów UDP na porcie 514
    volumes:
      - syslog-ng-logs:/var/log/docker_logs  # miejsce na logi
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro  # konfiguracja syslog-ng
    restart: unless-stopped

volumes:
  syslog-ng-logs:
